"""Initial migration

Revision ID: cbbb4ddecea4
Revises: 
Create Date: 2026-05-30 23:41:25.431191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cbbb4ddecea4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('DoctorID'), table_name='doctorschedule')
    op.drop_table('doctorschedule')
    op.drop_index(op.f('QR_code'), table_name='appointment')
    op.drop_table('appointment')
    op.drop_index(op.f('UserID'), table_name='doctor')
    op.drop_table('doctor')
    op.drop_index(op.f('Email'), table_name='user')
    op.drop_table('user')
    op.drop_table('notification')
    op.drop_table('auditlog')
    op.drop_table('clinic')
    op.drop_index(op.f('OPD_Id'), table_name='patient')
    op.drop_index(op.f('UserID'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('UserID'), table_name='clinic_staff')
    op.drop_table('clinic_staff')
    op.drop_table('medical_record')
    op.drop_table('livequeue')
    op.drop_index(op.f('DoctorID'), table_name='doctor_clinic_assignment')
    op.drop_table('doctor_clinic_assignment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_clinic_assignment',
    sa.Column('AssignmentID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('DoctorID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ClinicID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ClinicID'], ['clinic.ClinicID'], name=op.f('doctor_clinic_assignment_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['DoctorID'], ['doctor.Doctor_ID'], name=op.f('doctor_clinic_assignment_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('AssignmentID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('DoctorID'), 'doctor_clinic_assignment', ['DoctorID', 'ClinicID'], unique=True)
    op.create_table('livequeue',
    sa.Column('LiveQueueID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('AppointmentID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('DoctorID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('PatientID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('QueuePosition', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ArrivalTime', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('Status', mysql.ENUM('Waiting', 'In Consultation', 'Skipped', 'Completed'), server_default=sa.text("'Waiting'"), nullable=False),
    sa.ForeignKeyConstraint(['AppointmentID'], ['appointment.Appointment_ID'], name=op.f('livequeue_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['DoctorID'], ['doctor.Doctor_ID'], name=op.f('livequeue_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['PatientID'], ['patient.Patient_ID'], name=op.f('livequeue_ibfk_3'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('LiveQueueID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('medical_record',
    sa.Column('Record_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Appointment_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Patient_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Doctor_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ConsultationNotes', mysql.TEXT(), nullable=True),
    sa.Column('Prescription', mysql.TEXT(), nullable=True),
    sa.Column('RecordDate', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['Appointment_ID'], ['appointment.Appointment_ID'], name=op.f('medical_record_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Doctor_ID'], ['doctor.Doctor_ID'], name=op.f('medical_record_ibfk_3'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Patient_ID'], ['patient.Patient_ID'], name=op.f('medical_record_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Record_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('clinic_staff',
    sa.Column('Staff_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Phone_No', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('JobTitle', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ClinicID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ClinicID'], ['clinic.ClinicID'], name=op.f('clinic_staff_ibfk_2')),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], name=op.f('clinic_staff_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Staff_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('UserID'), 'clinic_staff', ['UserID'], unique=True)
    op.create_table('patient',
    sa.Column('Patient_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('OPD_Id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Phone_No', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('DateOfBirth', sa.DATE(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], name=op.f('patient_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Patient_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('UserID'), 'patient', ['UserID'], unique=True)
    op.create_index(op.f('OPD_Id'), 'patient', ['OPD_Id'], unique=True)
    op.create_table('clinic',
    sa.Column('ClinicID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('OperatingDays', mysql.VARCHAR(length=100), server_default=sa.text("'Weekdays'"), nullable=True),
    sa.Column('StartTime', mysql.TIME(), server_default=sa.text("'08:00:00'"), nullable=True),
    sa.Column('EndTime', mysql.TIME(), server_default=sa.text("'15:00:00'"), nullable=True),
    sa.Column('MaxPatients', mysql.INTEGER(), server_default=sa.text("'100'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ClinicID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('auditlog',
    sa.Column('LogID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Action', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Details', mysql.TEXT(), nullable=True),
    sa.Column('Timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], name=op.f('auditlog_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('LogID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('notification',
    sa.Column('Notification_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Patient_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Message', mysql.TEXT(), nullable=False),
    sa.Column('NotificationType', mysql.ENUM('SMS', 'Email'), nullable=False),
    sa.Column('Status', mysql.ENUM('Sent', 'Failed', 'Pending'), server_default=sa.text("'Pending'"), nullable=False),
    sa.Column('Sent_Time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['Patient_ID'], ['patient.Patient_ID'], name=op.f('notification_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Notification_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('UserID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Role', mysql.ENUM('Patient', 'Doctor', 'Staff', 'Admin'), nullable=False),
    sa.Column('Status', mysql.ENUM('Active', 'Pending', 'Disabled'), server_default=sa.text("'Pending'"), nullable=False),
    sa.Column('CreatedAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('UserID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('Email'), 'user', ['Email'], unique=True)
    op.create_table('doctor',
    sa.Column('Doctor_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Phone_No', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('Speciality', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('AverageConsultationMinutes', mysql.INTEGER(), server_default=sa.text("'10'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], name=op.f('doctor_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Doctor_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('UserID'), 'doctor', ['UserID'], unique=True)
    op.create_table('appointment',
    sa.Column('Appointment_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Patient_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ClinicID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Doctor_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('AppointmentDate', sa.DATE(), nullable=False),
    sa.Column('AppointmentTime', mysql.TIME(), nullable=True),
    sa.Column('Queue_Number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('QR_code', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Status', mysql.ENUM('Pending Allocation', 'Allocated', 'Arrived', 'In Progress', 'Completed', 'Cancelled', 'Skipped'), server_default=sa.text("'Pending Allocation'"), nullable=False),
    sa.Column('CreatedAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['ClinicID'], ['clinic.ClinicID'], name=op.f('fk_appointment_clinic'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Doctor_ID'], ['doctor.Doctor_ID'], name=op.f('appointment_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Patient_ID'], ['patient.Patient_ID'], name=op.f('appointment_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Appointment_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('QR_code'), 'appointment', ['QR_code'], unique=True)
    op.create_table('doctorschedule',
    sa.Column('ScheduleID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('DoctorID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('AvailableDate', sa.DATE(), nullable=False),
    sa.Column('StartTime', mysql.TIME(), nullable=False),
    sa.Column('EndTime', mysql.TIME(), nullable=False),
    sa.Column('Status', mysql.ENUM('Available', 'Booked', 'Unavailable'), server_default=sa.text("'Available'"), nullable=True),
    sa.Column('max_patients', mysql.INTEGER(), server_default=sa.text("'10'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['DoctorID'], ['doctor.Doctor_ID'], name=op.f('doctorschedule_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ScheduleID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('DoctorID'), 'doctorschedule', ['DoctorID', 'AvailableDate', 'StartTime'], unique=True)
    # ### end Alembic commands ###
